node:
  build: .
  command: npm start
  environment:
    NODE_ENV: development
    APP_PORT: 3000
  ports:
    - "14290:3000"
  volumes:
    - ./src:/var/www/src
    - ./config:/var/www/config
    - ./test:/var/www/test
    - ./coverage:/var/www/covreporter
    - ./package.json:/var/www/package.json
    - ./index.js:/var/www/index.js
  links:
    - redis
redis:
  image: redis:2.8
